spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invoicing
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true

invoicing-system:
  database: memory