spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/Invoicing
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

invoicing-system:
  database: jpa