server:
  port: 7777

invoicing-system:
  allowedOrigins: http://localhost:4200
  csrf:
    enabled: true
  database:
    type: memory
logging:
  level:
    org:
      flywaydb: DEBUG
    pl:
      futurecollars:
        invoicing:
          configuration: DEBUG
          db: DEBUG
    root: INFO
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    flyway:
      enabled: false