spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invoicing
    username: postgres
    password: Coronka5%2022
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true

invoicing-system:
  database:
    type: sql
