server:
  port: 7777

invoicing-system:
  database:
    type: memory
logging:
  level:
    pl:
      futurecollars:
        invoicing:
          configuration: DEBUG
          db: DEBUG
    root: INFO
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER