name: CI

on:
  push:
    branches: [ 'task_[0-9]+\/.*' ]
  pull_request:
    branches: [ 'task_[0-9]+\/.*' ]
  pull_request_target:
    branches:
      - 'task_[0-9]+\/.*'
  

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses:  actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Mark gradlew as executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
